[package]
name = "parser"
version = "0.1.0"
edition = "2021"
[dev-dependencies]
syntax = { path = "../syntax", features = ["test_active"] }


[dependencies]
combine = "*"
syntax = { path = "../syntax" }
regex = "*"